feat: recursive copying with --up
sindresorhus/cpy pull request #89
Opened 2021-08-02 22:11 UTC by netrules

2021-08-02 22:13 UTC, netrules commented
needed for https://github.com/sindresorhus/cpy-cli/pull/33

2022-02-27 09:28 UTC, sindresorhus requested changes

2022-02-27 09:28 UTC, sindresorhus commented on index.d.ts
> +	readonly up?: boolean;
I don't think this is a good option name. Maybe `trimPathComponents` or something.

2022-02-27 09:28 UTC, sindresorhus commented on index.js
> +  return path.join(path.normalize(source).split(path.sep).slice(up));
Use tab-indentation.

2022-02-27 09:28 UTC, sindresorhus commented on index.js
> +  if (up === true) {
This case is not documented.

2022-02-27 09:29 UTC, sindresorhus commented
This will need tests.

2022-02-27 09:49 UTC, sindresorhus commented
Note that things have changed since you started this: https://github.com/sindresorhus/cpy/releases/tag/v9.0.0

2022-03-16 18:46 UTC, tornadia approved these changes
@sindresorhus please see changes commited

2022-03-19 14:00 UTC, sindresorhus requested changes

2022-03-19 14:00 UTC, sindresorhus commented on index.d.ts
> +	@default 0
Missing the example from the readme.

2022-08-29 16:51 UTC, sgtrusty commented
Sorry, been a bit busy. Gonna check em out and jump on it, thanks @sindresorhus

2023-05-02 18:23 UTC, sindresorhus commented on readme.md
> +will be flattened to a reduced structure another `destination/flatSourceFiles` path.
Don't hard-wrap.

This is missing from index.d.ts

And I think it needs a rewrite. I don't really understand what it's trying to say.

2024-07-04 15:17 UTC, closed without merging