Fix recursive bugs
sindresorhus/cpy pull request #92
Opened 2021-10-04 22:39 UTC by Idered

This PR fixes 2 bugs:
- #91
- negative patterns not working

This PR completes my work on recursive feature. 

I'm also attaching a small migration guide bellow

---

# Breaking changes & examples

## Recursive by default

- `parents` option was removed 
- to get flat list of files use `flat: true` option

Example directory structure:
```
- .github/workflows/main.yml
- .github/funding.yml
```

Command: `cpy('.github/**', 'dest')`

Old output:
```
- dest/funding.yml
- dest/main.yml
```
New output: 
```
- dest/workflows/main.yml
- dest/main.yml
```

## Recreate old `parents: true`

Example directory structure:
```
- .github/workflows/main.yml
- .github/funding.yml
```

Old:
`cpy('.github/**', 'dest', {parents: true})`

New:
`cpy('.github', 'dest')`

Output:
```
- dest/.github/workglows/main.yml
- dest/.github/funding.yml
```

## Recreate old `parents: false`
Example directory structure:
```
- .github/workflows/main.yml
- .github/funding.yml
```

Old:
`cpy('.github/**', 'dest', {parents: false})`

New:
`cpy('.github', 'dest', {flat: true})`

Output:
```
- dest/main.yml
- dest/funding.yml
```

## Copy all package.json and preserve folder structure

Old: 
`cpy('node_modules/**/package.json', 'dest', {parents: true})`

Old output:
![](https://i.imgur.com/sHOe35T.png)

New: 
`cpy('node_modules/**/package.json', 'dest')`

New output:
![](https://i.imgur.com/pYJEK2T.png)

> Ignore colors, those are git changes

2021-10-05 08:48 UTC, sindresorhus commented
Thanks for working on this. Would you be able to add some tests for the bugs being fixed?

2021-10-05 08:48 UTC, sindresorhus commented
> Can I get hacktoberfest-accepted label on this?

✅

2021-10-05 08:55 UTC, sindresorhus commented on index.js
> +	}
This would be a good place to use `Array#flatMap`.

2021-10-05 08:59 UTC, sindresorhus requested changes

2021-10-05 08:59 UTC, sindresorhus commented on index.js
> +	if (entry.pattern.isDirectory && path.relative(options.cwd, entry.path).startsWith('..')) {
This check will not work correctly if `options.cwd` and `entry.path` are on different partitions on Windows, see: https://github.com/sindresorhus/import-local/pull/12

2021-10-05 08:59 UTC, sindresorhus commented on index.js
> +	if (!entry.pattern.isDirectory && entry.path === entry.relativePath) {
It would be good to have a short code comment on both of these `if`'s on what kind of case they handle.

2021-11-07 17:32 UTC, sindresorhus commented
Bump :)

2021-12-14 09:48 UTC, iiLearner commented
@Idered would you be able to have a follow up to this as its blocking https://github.com/sindresorhus/cpy/issues/98 :)

2022-01-09 10:20 UTC, sindresorhus commented on index.js
> +*/
```suggestion
/**
Expand patterns like `'node_modules/{globby,micromatch}'` into `['node_modules/globby', 'node_modules/micromatch']`.

@param {string[]} patterns
@returns {string[]}
*/
```

2022-02-27 09:25 UTC, merged

2022-05-03 07:01 UTC, thetutlage commented
This PR introduces a regression. Following is a snippet from the PR original content.

## Recreate old parents: true
Example directory structure:

- `.github/workflows/main.yml`
- `.github/funding.yml`

Old:
```
cpy('.github/**', 'dest', {parents: true})
```

New:
```
cpy('.github', 'dest')
```

Output:

```
- dest/.github/workglows/main.yml
- dest/.github/funding.yml
```

----

How should I have the same output as previous `parents: true` while defining the file extensions as well.

Old:

```ts
cpy('.github/**/*.yml', 'dest', {parents: true})
```

Old Output:

```
- dest/.github/workglows/main.yml
- dest/.github/funding.yml
```

New:

```ts
cpy('.github/**/*.yaml', 'dest')
```

New Output:

```
- dest/workglows/main.yml
- dest/funding.yml
```